#!/usr/bin/env bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
GRADLEW="${SCRIPT_DIR}/gradlew"
pushd ${SCRIPT_DIR} >/dev/null

$GRADLEW run --quiet --console=plain

popd >/dev/null